name: tests

on:
  push:
  pull_request:

jobs:

  basic-tests-linux:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
    env:
      GITHUB_OS: linux
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2.2.2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Test with nose
      run: |
        pip install nose
        nosetests

  basic-tests-macos:

    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [3.8]
    env:
      GITHUB_OS: macos
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2.2.2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Test with nose
      run: |
        pip install nose
        nosetests
#    - name: Test with pytest
#      run: |
#        pip install pytest
#        pytest

  basic-tests-windows:

    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.8]
    env:
      GITHUB_OS: windows
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2.2.2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Test with nose
      run: |
        pip install nose
        nosetests
